// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD-HrG6Uog3wfhoWbQ-xW5tbSvr4FnFR0',
    appId: '1:404667908068:web:238241c9508d932099d1f1',
    messagingSenderId: '404667908068',
    projectId: 'mony-nest',
    authDomain: 'mony-nest.firebaseapp.com',
    storageBucket: 'mony-nest.firebasestorage.app',
    measurementId: 'G-YTBRRHVCMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQiz88ZUs75HoxZa5D5-sIqg4DOmqGbM',
    appId: '1:404667908068:android:e1c2d317af5054d699d1f1',
    messagingSenderId: '404667908068',
    projectId: 'mony-nest',
    storageBucket: 'mony-nest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkonRmQjMMaba-6gFQUzil2QDq7IFYOFM',
    appId: '1:404667908068:ios:49be73bd9eedef7e99d1f1',
    messagingSenderId: '404667908068',
    projectId: 'mony-nest',
    storageBucket: 'mony-nest.firebasestorage.app',
    iosBundleId: 'com.example.moneyNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkonRmQjMMaba-6gFQUzil2QDq7IFYOFM',
    appId: '1:404667908068:ios:49be73bd9eedef7e99d1f1',
    messagingSenderId: '404667908068',
    projectId: 'mony-nest',
    storageBucket: 'mony-nest.firebasestorage.app',
    iosBundleId: 'com.example.moneyNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD-HrG6Uog3wfhoWbQ-xW5tbSvr4FnFR0',
    appId: '1:404667908068:web:ea5b74bf05318b6499d1f1',
    messagingSenderId: '404667908068',
    projectId: 'mony-nest',
    authDomain: 'mony-nest.firebaseapp.com',
    storageBucket: 'mony-nest.firebasestorage.app',
    measurementId: 'G-Z1MD1NFHC6',
  );
}
